# Bon, l'idée c'était de faire tourner automatiquement la création des tuiles quand quelqu'un ajoute dans une PR
# Sauf que j'ai envie de faire tourner ça sur le serveur, pas sur github action. Car il faut installer pmtiles, etc
# Donc le plus simple c'est de taper une route /update-tiles, comme on fait déjà pour d'autre
# ... sauf qu'il faut faire tourner cette route sur la base d'un fichier MAJ par la PR, donc pas du code de master mais de la branche
# Donc il faut un système de déploiement du code github sur notre serveur, un système d'environnement, un mini-heroku

name: Build cycleHighways PMTiles

on:
  push:
    branches: ['master']
    paths:
      - 'cycleHighways.ts'
  pull_request:
    branches: ['master']
    types: [opened, synchronize]
    paths:
      - 'cycleHighways.ts'

permissions:
  contents: read

jobs:
  build-tiles:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Deno install
        run: deno install
      - name: Run script
        run: deno --allow-net --allow-read --allow-write ./cycleHighways.ts
